// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {traymodel} from '../models';
import {config} from '../models';
import {context} from '../models';
import {main} from '../models';

export function ForceExitAll():Promise<traymodel.ForceExitResult>;

export function ForceStopAgent():Promise<traymodel.OperationResult>;

export function ForceStopHelper():Promise<traymodel.OperationResult>;

export function GetAgentForm():Promise<config.AgentForm>;

export function GetHelperForm():Promise<config.HelperForm>;

export function GetOverview():Promise<traymodel.Overview>;

export function GetTraySettings():Promise<traymodel.TraySettings>;

export function OpenLocation(arg1:traymodel.LocationKind):Promise<traymodel.OperationResult>;

export function RestartAgent():Promise<traymodel.OperationResult>;

export function RestartHelper():Promise<traymodel.OperationResult>;

export function SaveAgent(arg1:config.AgentForm):Promise<traymodel.ConfigApplyResult>;

export function SaveAndRestartAgent(arg1:config.AgentForm):Promise<traymodel.ConfigApplyResult>;

export function SaveHelper(arg1:config.HelperForm):Promise<traymodel.ConfigApplyResult>;

export function SaveTraySettings(arg1:traymodel.TraySettings):Promise<traymodel.OperationResult>;

export function Shutdown(arg1:context.Context):Promise<void>;

export function StartAgent():Promise<traymodel.OperationResult>;

export function StartHelper():Promise<traymodel.OperationResult>;

export function Startup(arg1:context.Context):Promise<main.BackendStartup>;

export function StopAgent():Promise<traymodel.OperationResult>;

export function StopHelper():Promise<traymodel.OperationResult>;

export function ValidateAgent(arg1:config.AgentForm):Promise<Array<config.FieldError>>;

export function ValidateHelper(arg1:config.HelperForm):Promise<Array<config.FieldError>>;
