// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function ChooseLocalTaskRoot(arg1) {
  return window['go']['main']['Backend']['ChooseLocalTaskRoot'](arg1);
}

export function CreateLocalTask(arg1) {
  return window['go']['main']['Backend']['CreateLocalTask'](arg1);
}

export function ExecuteLocalDelete(arg1) {
  return window['go']['main']['Backend']['ExecuteLocalDelete'](arg1);
}

export function ForceExitAll() {
  return window['go']['main']['Backend']['ForceExitAll']();
}

export function ForceStopAgent() {
  return window['go']['main']['Backend']['ForceStopAgent']();
}

export function ForceStopHelper() {
  return window['go']['main']['Backend']['ForceStopHelper']();
}

export function GetAgentForm() {
  return window['go']['main']['Backend']['GetAgentForm']();
}

export function GetHelperForm() {
  return window['go']['main']['Backend']['GetHelperForm']();
}

export function GetLocalImagePreview(arg1) {
  return window['go']['main']['Backend']['GetLocalImagePreview'](arg1);
}

export function GetOverview() {
  return window['go']['main']['Backend']['GetOverview']();
}

export function GetTraySettings() {
  return window['go']['main']['Backend']['GetTraySettings']();
}

export function ListLocalGroups(arg1) {
  return window['go']['main']['Backend']['ListLocalGroups'](arg1);
}

export function ListLocalTasks(arg1) {
  return window['go']['main']['Backend']['ListLocalTasks'](arg1);
}

export function OpenLocation(arg1) {
  return window['go']['main']['Backend']['OpenLocation'](arg1);
}

export function PrepareLocalDelete(arg1) {
  return window['go']['main']['Backend']['PrepareLocalDelete'](arg1);
}

export function RestartAgent() {
  return window['go']['main']['Backend']['RestartAgent']();
}

export function RestartHelper() {
  return window['go']['main']['Backend']['RestartHelper']();
}

export function SaveAgent(arg1) {
  return window['go']['main']['Backend']['SaveAgent'](arg1);
}

export function SaveAndRestartAgent(arg1) {
  return window['go']['main']['Backend']['SaveAndRestartAgent'](arg1);
}

export function SaveHelper(arg1) {
  return window['go']['main']['Backend']['SaveHelper'](arg1);
}

export function SaveLocalReview(arg1) {
  return window['go']['main']['Backend']['SaveLocalReview'](arg1);
}

export function SaveTraySettings(arg1) {
  return window['go']['main']['Backend']['SaveTraySettings'](arg1);
}

export function Shutdown(arg1) {
  return window['go']['main']['Backend']['Shutdown'](arg1);
}

export function StartAgent() {
  return window['go']['main']['Backend']['StartAgent']();
}

export function StartHelper() {
  return window['go']['main']['Backend']['StartHelper']();
}

export function StartLocalAnalysis(arg1) {
  return window['go']['main']['Backend']['StartLocalAnalysis'](arg1);
}

export function Startup(arg1) {
  return window['go']['main']['Backend']['Startup'](arg1);
}

export function StopAgent() {
  return window['go']['main']['Backend']['StopAgent']();
}

export function StopHelper() {
  return window['go']['main']['Backend']['StopHelper']();
}

export function ValidateAgent(arg1) {
  return window['go']['main']['Backend']['ValidateAgent'](arg1);
}

export function ValidateHelper(arg1) {
  return window['go']['main']['Backend']['ValidateHelper'](arg1);
}
