[package]
name = "dedup-desktop-ui"
version.workspace = true
edition.workspace = true
license.workspace = true
publish.workspace = true

[lib]
path = "src/lib.rs"

[dependencies]
dedup-core = { path = "../core" }
dedup-desktop-core = { path = "../desktop-core" }
image = { workspace = true, features = ["png", "ico"] }
slint.workspace = true
tokio.workspace = true

[build-dependencies]
slint-build.workspace = true

[dev-dependencies]
i-slint-backend-testing = { version = "=1.17.1", features = ["renderer-software"] }
