<#
.SYNOPSIS
使用固定 bindgen 0.72.1 与 LLVM 21.1.8 重新生成 FFmpeg 8.0.1 类型绑定。

.DESCRIPTION
普通构建只消费已提交的 bindings_8_0_1.rs，不需要 LLVM 或 FFmpeg 头文件。本脚本
仅用于有意升级或复核绑定；函数全部 blocklist，动态函数指针由 ffi.rs 明确声明。
#>
[CmdletBinding()]
param(
    [Parameter(Mandatory)]
    [string] $IncludeRoot,

    [Parameter(Mandatory)]
    [string] $LibClangDirectory,

    [Parameter(Mandatory)]
    [string] $BindgenExe,

    [string] $Output = 'crates\media-ffmpeg\src\bindings_8_0_1.rs'
)

$ErrorActionPreference = 'Stop'
$repositoryRoot = Split-Path -Parent $PSScriptRoot
$wrapper = Join-Path $repositoryRoot 'crates\media-ffmpeg\wrapper.h'
$outputPath = [IO.Path]::GetFullPath((Join-Path $repositoryRoot $Output))
$temporaryOutput = "$outputPath.generated"
$manifest = Get-Content -LiteralPath (Join-Path $repositoryRoot 'third_party\ffmpeg-dependency.json') -Raw | ConvertFrom-Json

$env:LIBCLANG_PATH = [IO.Path]::GetFullPath($LibClangDirectory)
$env:RUST_LOG = 'error'
$bindgenPath = [IO.Path]::GetFullPath($BindgenExe)
$includePath = [IO.Path]::GetFullPath($IncludeRoot)

$arguments = @(
    $wrapper,
    '--output', $temporaryOutput,
    '--rust-target', '1.97',
    '--formatter', 'rustfmt',
    '--generate', 'types,vars',
    '--no-layout-tests',
    '--allowlist-type', '^AV(Rational|FormatContext|Stream|CodecParameters|CodecContext|Codec|Packet|Frame|InputFormat|Dictionary|MediaType|PixelFormat|CodecID)$',
    '--allowlist-type', '^SwsContext$',
    '--allowlist-var', '^AV_(TIME_BASE|NOPTS_VALUE)$',
    '--allowlist-var', '^AVMEDIA_TYPE_VIDEO$',
    '--allowlist-var', '^AV_PIX_FMT_RGB24$',
    '--allowlist-var', '^AVSEEK_FLAG_BACKWARD$',
    '--ignore-functions',
    '--',
    "-I$includePath",
    '-D__STDC_CONSTANT_MACROS'
)

& $bindgenPath @arguments
if ($LASTEXITCODE -ne 0) {
    throw "bindgen failed with exit code $LASTEXITCODE"
}

$generated = Get-Content -LiteralPath $temporaryOutput -Raw
$header = @"
// @generated by bindgen 0.72.1 with LLVM 21.1.8.
// FFmpeg archive: $($manifest.archive_name)
// FFmpeg archive SHA-256: $($manifest.archive_sha256)
// Do not edit by hand; run scripts/generate-ffmpeg-bindings.ps1.

"@
[IO.File]::WriteAllText($outputPath, $header + $generated, [Text.UTF8Encoding]::new($false))
Remove-Item -LiteralPath $temporaryOutput -Force
Write-Output "Generated $outputPath"
